controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    defaults: { _locale: 'en' }
    requirements:
        _locale: 'en|ru'

switch_language:
    path: /switch-language/{locale}
    controller: App\Controller\LanguageController::switchLanguage
    requirements:
        locale: 'en|ru'